### ISSUE TITLE
Support plain "key value" input files

### ISSUE THREAD

**Issue by ash2k** [wryun/rjsone#12]
Would be useful to support files of the following format:
```
key1 value1
key2 some value 2
key3 42
```
Interpreted as if it was this YAML (see the first link for details):
```yaml
key1: "value1"
key2: "some value 2"
key3: "42"
```
This is the format produced by "workplace status" commands - see [`--workspace_status_command program`](https://docs.bazel.build/versions/master/user-manual.html#flag--workspace_status_command). Key/value pairs then can be consumed by Bazel rules, typically for stamping (introducing controlled non-determinism into the build). Typical example is putting git commit sha into a docker image tag (see `stamp` in [`container_push`](https://github.com/bazelbuild/rules_docker#container_push-1) in rules_docker), etc.

I'd like to add stamping support to rjsone rule for bazel (https://github.com/atlassian/bazel-tools/issues/12) and I have two options:
- write a helper program that translates the stamping format into yaml/json so that rjsone, invoked from the rule, can consume it as an additional context.
- modify rjsone to support this format so that rjsone rule can just pass the file(s), produced by some workspace status command, as additional contexts.

This issue is about the later approach. It may be a new flag for files in this formats or some modifier to existing flags. WDYT?

**Comment by wryun** [comment]
Hmm, but at the moment I've made some terrible crazy syntax for every argument (i.e. you can mix/match files, raw things, what kind of files). To be consistent, I don't really want to use a flag which would globally affect, it would have to be some kind of sigil... e.g. an '@' at the front means a bazel style file.

I guess... argh.

Clearly I should add bash syntax while I'm at it.

```
export FOO=1
```

?

**Comment by wryun** [comment]
How do you feel about using sed?

e.g.

```
sed 's/^\([^ ]*\)\(.*\)$/\1: "\2"/'
```
I'm surprised workspace_status_command doesn't at least support json input/output; can't find an issue about it, though.
